# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 15:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanji_name', models.CharField(max_length=50)),
                ('kanji_meaning', models.CharField(max_length=200)),
                ('readings', models.CharField(max_length=200, null=True)),
                ('on_kun_readings', models.CharField(max_length=200, null=True)),
                ('strokes', models.IntegerField(null=True)),
                ('grade', models.IntegerField(null=True)),
                ('newspaper_frequency', models.IntegerField(null=True)),
                ('jlpt_level', models.IntegerField(null=True)),
                ('jinmeiyo', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KnownKanji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('selected_kanji', models.BooleanField(default=False)),
                ('number_of_chosen_words', models.IntegerField(null=True)),
                ('kanji', models.ManyToManyField(to='manageset.Kanji')),
            ],
        ),
        migrations.CreateModel(
            name='KnownWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('tier_level', models.IntegerField()),
                ('last_practiced', models.DateTimeField(blank=True)),
                ('time_until_review', models.FloatField(null=True)),
                ('times_answered_correct', models.IntegerField(default=0)),
                ('times_answered_wrong', models.IntegerField(default=0)),
                ('correct_percentage', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name=b'pub_date')),
                ('times_practiced', models.IntegerField()),
                ('kanji', models.ManyToManyField(blank=True, to='manageset.Kanji')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_words_practiced_today', models.IntegerField(default=0)),
                ('words_practied_today_time_marker', models.DateTimeField(auto_now_add=True)),
                ('most_words_practiced_in_day', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_sets', models.ManyToManyField(blank=True, to='manageset.Sets')),
            ],
        ),
        migrations.CreateModel(
            name='WordMeanings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='WordPos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_word', models.CharField(max_length=300)),
                ('meaning', models.CharField(max_length=500)),
                ('hiragana', models.CharField(max_length=301)),
                ('frequency', models.IntegerField(blank=True, db_index=True, null=True)),
                ('frequency_two', models.IntegerField(blank=True, db_index=True, null=True)),
                ('combined_frequency', models.IntegerField(blank=True, db_index=True, null=True)),
                ('frequency_thousand', models.IntegerField(blank=True, db_index=True, null=True)),
                ('part_of_speech', models.CharField(max_length=200, null=True)),
                ('duplicate_word', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=True)),
                ('jlpt_level', models.IntegerField(blank=True, db_index=True, null=True)),
                ('kanji', models.ManyToManyField(blank=True, to='manageset.Kanji')),
            ],
        ),
        migrations.AddField(
            model_name='wordpos',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageset.Words'),
        ),
        migrations.AddField(
            model_name='wordmeanings',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageset.Words'),
        ),
        migrations.AddField(
            model_name='sets',
            name='words',
            field=models.ManyToManyField(blank=True, to='manageset.Words'),
        ),
        migrations.AddField(
            model_name='knownwords',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageset.UserProfile'),
        ),
        migrations.AddField(
            model_name='knownwords',
            name='words',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageset.Words'),
        ),
        migrations.AddField(
            model_name='knownkanji',
            name='user_profile',
            field=models.ManyToManyField(to='manageset.UserProfile'),
        ),
    ]
