# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageset', '0002_sentence'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentenceOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='sentence',
            name='sentence_owner',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='manageset.SentenceOwner'),
        ),
    ]
