# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageset', '0003_auto_20160306_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='sentence',
        ),
        migrations.AddField(
            model_name='sentence',
            name='comment_exists',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sentence',
            name='english_sentence',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sentence',
            name='japanese_sentence',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sentence',
            name='source_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sentence',
            name='source_url',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
