# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageset', '0004_auto_20160313_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='sentence_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageset.SentenceOwner'),
        ),
        migrations.AlterField(
            model_name='sentenceowner',
            name='name',
            field=models.CharField(default=b' ', max_length=50, null=True),
        ),
    ]
