# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageset', '0007_auto_20160313_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='sentence_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manageset.SentenceOwner'),
        ),
    ]
