# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageset', '0008_auto_20160313_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='sentence_scrape',
            field=models.BooleanField(default=False),
        ),
    ]
