# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageset', '0009_words_sentence_scrape'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='audio',
            field=models.URLField(null=True),
        ),
    ]
