# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-01 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageset', '0012_auto_20160402_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanji',
            name='master_order',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sentence',
            name='in_production',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='words',
            name='master_order',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='words',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
