# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-25 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageset', '0015_knownkanji_kanji_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='sets',
            name='level',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sets',
            name='sub_level',
            field=models.IntegerField(null=True),
        ),
    ]
