# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-15 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageset', '0017_auto_20161202_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='words_practied_today_time_marker',
            new_name='words_practiced_today_time_marker',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_correct_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_incorrect_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_words_reviewed_ever',
            field=models.IntegerField(default=0),
        ),
    ]
