# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-06 00:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageset', '0018_auto_20161215_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_status', models.BooleanField(default=False)),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name=b'creation_time')),
                ('sets_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageset.Sets')),
            ],
        ),
        migrations.RemoveField(
            model_name='knownkanji',
            name='kanji',
        ),
        migrations.RemoveField(
            model_name='knownkanji',
            name='number_of_chosen_words',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_sets',
        ),
        migrations.AddField(
            model_name='usersets',
            name='user_profile_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageset.UserProfile'),
        ),
    ]
