# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-04 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageset', '0019_auto_20170106_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words_studied_count', models.IntegerField(default=0)),
                ('words_completed_count', models.IntegerField(default=0)),
                ('words_reviewed_count', models.IntegerField(default=0)),
                ('kanji_studied_count', models.IntegerField(default=0)),
                ('kanji_completed_count', models.IntegerField(default=0)),
                ('last_modified', models.DateField()),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageset.UserProfile')),
            ],
        ),
    ]
