# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-04 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageset', '0020_analyticslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticslog',
            name='kanji_reviewed_today_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analyticslog',
            name='words_reviewed_today_count',
            field=models.IntegerField(default=0),
        ),
    ]
