# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-08 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageset', '0021_auto_20170204_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analyticslog',
            old_name='kanji_reviewed_today_count',
            new_name='kanji_studied_count_today',
        ),
        migrations.RenameField(
            model_name='analyticslog',
            old_name='words_reviewed_today_count',
            new_name='words_reviewed_count_today',
        ),
        migrations.AddField(
            model_name='analyticslog',
            name='words_studied_count_today',
            field=models.IntegerField(default=0),
        ),
    ]
