# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-15 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageset', '0026_remove_usersets_test_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('words', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageset.Words')),
            ],
        ),
        migrations.AlterField(
            model_name='sentence',
            name='words',
            field=models.ManyToManyField(related_name='word_sentence', to='manageset.Words'),
        ),
    ]
