# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-15 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageset', '0027_auto_20170415_0839'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WordQuestions',
            new_name='WordQuestion',
        ),
    ]
