# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-15 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageset', '0028_auto_20170415_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='part_of_speech',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
