# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-15 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageset', '0029_auto_20170415_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanji',
            name='order_from_words',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='wordquestion',
            name='words',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_question', to='manageset.Words'),
        ),
    ]
