# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-15 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageset', '0030_auto_20170415_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='knownkanji',
            name='user_profile_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_fk', to='manageset.UserProfile'),
        ),
    ]
